<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CoffeeTracker.Domain\CoffeeTracker.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.3.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*" />
    <PackageReference Include="Whisper.net" Version="*" />
    <PackageReference Include="Whisper.net.Runtime" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);MEAI001</NoWarn>
  </PropertyGroup>

</Project>
