// <auto-generated />
using System;
using CoffeeTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412110114_AddRoasterWebsiteUrl")]
    partial class AddRoasterWebsiteUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessoryBrewer", b =>
                {
                    b.Property<Guid>("AccessoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompatibleBrewersId")
                        .HasColumnType("uuid");

                    b.HasKey("AccessoriesId", "CompatibleBrewersId");

                    b.HasIndex("CompatibleBrewersId");

                    b.ToTable("AccessoryBrewer");
                });

            modelBuilder.Entity("BeanCountry", b =>
                {
                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginCountriesId")
                        .HasColumnType("uuid");

                    b.HasKey("BeanId", "OriginCountriesId");

                    b.HasIndex("OriginCountriesId");

                    b.ToTable("BeanCountry");
                });

            modelBuilder.Entity("BeanFlavorNote", b =>
                {
                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlavorNotesId")
                        .HasColumnType("uuid");

                    b.HasKey("BeanId", "FlavorNotesId");

                    b.HasIndex("FlavorNotesId");

                    b.ToTable("BeanFlavorNote");
                });

            modelBuilder.Entity("BrewLogAccessory", b =>
                {
                    b.Property<Guid>("AccessoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewLogEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("AccessoriesId", "BrewLogEntryId");

                    b.HasIndex("BrewLogEntryId");

                    b.ToTable("BrewLogAccessory");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Accessory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Altitude")
                        .HasColumnType("integer");

                    b.Property<decimal>("BagWeight")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProcessingMethod")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("RoastDate")
                        .HasColumnType("date");

                    b.Property<string>("RoastProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variety")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.BrewLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentIdeas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BrewTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BrewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BrewerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Dose")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("GrindSize")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("GrinderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WaterAmount")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("WaterTemperature")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.HasIndex("BrewerId");

                    b.HasIndex("GrinderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("BrewLogEntries");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Brewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Brewers");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IsoAlpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("IsoNumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsoAlpha2")
                        .IsUnique()
                        .HasFilter("\"IsoAlpha2\" <> ''");

                    b.HasIndex("IsoNumericCode")
                        .IsUnique()
                        .HasFilter("\"IsoNumericCode\" <> ''");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.FlavorNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FlavorNotes");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Grinder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Grinders");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BrewerId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Roaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("bytea");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Roasters");
                });

            modelBuilder.Entity("AccessoryBrewer", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Accessory", null)
                        .WithMany()
                        .HasForeignKey("AccessoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Brewer", null)
                        .WithMany()
                        .HasForeignKey("CompatibleBrewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeanCountry", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Bean", null)
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("OriginCountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeanFlavorNote", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Bean", null)
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.FlavorNote", null)
                        .WithMany()
                        .HasForeignKey("FlavorNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrewLogAccessory", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Accessory", null)
                        .WithMany()
                        .HasForeignKey("AccessoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.BrewLogEntry", null)
                        .WithMany()
                        .HasForeignKey("BrewLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Bean", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Roaster", "Roaster")
                        .WithMany("Beans")
                        .HasForeignKey("RoasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roaster");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.BrewLogEntry", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Bean", "Bean")
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Brewer", "Brewer")
                        .WithMany()
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Grinder", "Grinder")
                        .WithMany()
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bean");

                    b.Navigation("Brewer");

                    b.Navigation("Grinder");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Brewer", "Brewer")
                        .WithMany()
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Roaster", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Roaster", b =>
                {
                    b.Navigation("Beans");
                });
#pragma warning restore 612, 618
        }
    }
}
