// <auto-generated />
using System;
using CoffeeTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220072831_AddBrewer")]
    partial class AddBrewer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeanCountry", b =>
                {
                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginCountriesId")
                        .HasColumnType("uuid");

                    b.HasKey("BeanId", "OriginCountriesId");

                    b.HasIndex("OriginCountriesId");

                    b.ToTable("BeanCountry");
                });

            modelBuilder.Entity("BeanFlavorNote", b =>
                {
                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlavorNotesId")
                        .HasColumnType("uuid");

                    b.HasKey("BeanId", "FlavorNotesId");

                    b.HasIndex("FlavorNotesId");

                    b.ToTable("BeanFlavorNote");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Altitude")
                        .HasColumnType("integer");

                    b.Property<decimal>("BagWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProcessingMethod")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("RoastDate")
                        .HasColumnType("date");

                    b.Property<string>("RoastProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variety")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Brewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Brewers");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.FlavorNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FlavorNotes");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Roaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Roasters");
                });

            modelBuilder.Entity("BeanCountry", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Bean", null)
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("OriginCountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeanFlavorNote", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Bean", null)
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTracker.Domain.Entities.FlavorNote", null)
                        .WithMany()
                        .HasForeignKey("FlavorNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Bean", b =>
                {
                    b.HasOne("CoffeeTracker.Domain.Entities.Roaster", "Roaster")
                        .WithMany("Beans")
                        .HasForeignKey("RoasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roaster");
                });

            modelBuilder.Entity("CoffeeTracker.Domain.Entities.Roaster", b =>
                {
                    b.Navigation("Beans");
                });
#pragma warning restore 612, 618
        }
    }
}
