export {
  loadAccessoryDetailPage,
  loadAccessoryFormPage,
  loadBeanDetailPage,
  loadBeanFormPage,
  loadBrewLogDetailPage,
  loadBrewLogFormPage,
  loadBrewerDetailPage,
  loadBrewerFormPage,
  loadEquipmentPage,
  loadGrinderDetailPage,
  loadGrinderFormPage,
  loadRecipeDetailPage,
  loadRecipeFormPage,
  loadRoasterDetailPage,
  loadRoasterFormPage,
  preloadBeanFeatureRoutes,
  preloadBrewLogFeatureRoutes,
  preloadEquipmentFeatureRoutes,
  preloadRecipeFeatureRoutes,
  preloadRoasterFeatureRoutes,
} from '@/lib/routeRegistry'
